version: '3'

services:
  db:
    image: cockroachdb/cockroach:v22.1.1
    volumes:
      - ./local_cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    env_file:
      - .env
    command:
      - start-single-node
      - --insecure

  api:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true
